<a href="https://colab.research.google.com/github/Nikkkhhill97/Airbnb-Data-Analysis-Dashboard-Tableau-/blob/main/Data_Visualization_Tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import gdown


# ID for Chicago Dataset
chicago_file_id = '1CaIk9eAs9fDKhTGIUqCHImypDidDbj_1'

# ID for New Orleans Dataset
new_orleans_file_id = '1Ebmj5Wiw365oYEr0C3prIYN_QVlSHt-V'


print(" Downloading Chicago Data...")
url_chicago = f'https://drive.google.com/uc?id={chicago_file_id}'
gdown.download(url_chicago, 'chicago_data.csv', quiet=False)

print("\n⬇ Downloading New Orleans Data...")
url_no = f'https://drive.google.com/uc?id={new_orleans_file_id}'
gdown.download(url_no, 'new_orleans_data.csv', quiet=False)

# --- STEP 3: Read and Label them ---

# Read the CSVs
chicago_df = pd.read_csv('chicago_data.csv')
new_orleans_df = pd.read_csv('new_orleans_data.csv')

# Add a 'City' column so we know which row belongs to which city
chicago_df['City'] = 'Chicago'
new_orleans_df['City'] = 'New Orleans'

# --- STEP 4: Merge into one Master File ---

# Concatenate (stack them on top of each other)
df = pd.concat([chicago_df, new_orleans_df], ignore_index=True)

# Show the result
print(f"\nSuccess! Merged dataset has {len(df)} rows.")
print("Here is a preview:")
df.head()

 Downloading Chicago Data...

Downloading...
From: https://drive.google.com/uc?id=1CaIk9eAs9fDKhTGIUqCHImypDidDbj_1
To: /content/chicago_data.csv
100%|██████████| 18.7M/18.7M [00:00<00:00, 75.8MB/s]

⬇ Downloading New Orleans Data...

Downloading...
From: https://drive.google.com/uc?id=1Ebmj5Wiw365oYEr0C3prIYN_QVlSHt-V
To: /content/new_orleans_data.csv
100%|██████████| 22.1M/22.1M [00:00<00:00, 94.2MB/s]

Success! Merged dataset has 16104 rows.
Here is a preview:

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,City
0,19091,https://www.airbnb.com/rooms/19091,20250911031349,2025-09-11,city scrape,Fully Furnished Cozy Apartment,This cozy space is a wonder of post-Katrina re...,"NorthWest Carrollton, where this apartment is ...",https://a0.muscache.com/pictures/a5fdfd3b-5d81...,72880,...,4.68,4.91,"25-NSTR-11772, 25-OSTR-11151",f,1,1,0,0,2.72,Chicago
1,71624,https://www.airbnb.com/rooms/71624,20250911031349,2025-09-11,city scrape,Ravenwood Manor (Historic Bywater),You are in for a very unique stay in a neighbo...,"Ours is a neighborhood made up of artists, mus...",https://a0.muscache.com/pictures/37488608/8cc1...,367223,...,4.84,4.89,"21-RSTR-18609, 22-OSTR-20720",f,1,1,0,0,1.78,Chicago
2,74498,https://www.airbnb.com/rooms/74498,20250911031349,2025-09-11,city scrape,Maison Marais 1,Maison Marais 1 is a stylish one-bedroom apart...,"This is a vibrant, diverse neighborhood of mos...",https://a0.muscache.com/pictures/73591836/a1f5...,391462,...,4.67,4.85,23-XSTR-13082,f,3,3,0,0,3.75,Chicago
3,79536,https://www.airbnb.com/rooms/79536,20250911031349,2025-09-11,previous scrape,FeelAtHomeInNewOrleans-PrivateApt,"Safe, clean & functional!! Front porch and gat...","I love that it's down to earth, welcoming, his...",https://a0.muscache.com/pictures/f1037ebf-1573...,428362,...,4.56,4.87,"23-NSTR-15067, 24-OSTR-20882",t,1,1,0,0,4.57,Chicago
4,79609,https://www.airbnb.com/rooms/79609,20250911031349,2025-09-11,city scrape,Bywater's Original & Finest,The Art of Hospitality,"First settled in 1806, Bywater is known for it...",https://a0.muscache.com/pictures/5c5da2eb-7434...,428909,...,4.84,4.94,"23-ISTR-02823, 23-OSTR-02823",f,1,1,0,0,2.86,Chicago

In [ ]:
# 1. Clean the symbols again (just to be safe)
# We treat the column as a string, replace '$' and ',' with nothing.
df['price'] = df['price'].astype(str).str.replace('$', '').str.replace(',', '')

# 2. Convert to numeric with 'coerce'
# This is the MAGIC FIX. It turns the string "nan" back into a proper null value.
df['price'] = pd.to_numeric(df['price'], errors='coerce')

# 3. Check how many prices are missing
missing_count = df['price'].isnull().sum()
print(f"Prices cleaned! Rows with missing prices: {missing_count}")

# 4. (Recommended) Drop rows where Price is missing
# A listing with no price is useless for our analysis, so let's remove them.
df = df.dropna(subset=['price'])

print("Price column fixed and ready.")
df.head()

Prices cleaned! Rows with missing prices: 2046
Price column fixed and ready.

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,City
0,19091,https://www.airbnb.com/rooms/19091,20250911031349,2025-09-11,city scrape,Fully Furnished Cozy Apartment,This cozy space is a wonder of post-Katrina re...,"NorthWest Carrollton, where this apartment is ...",https://a0.muscache.com/pictures/a5fdfd3b-5d81...,72880,...,4.68,4.91,"25-NSTR-11772, 25-OSTR-11151",f,1,1,0,0,2.72,Chicago
1,71624,https://www.airbnb.com/rooms/71624,20250911031349,2025-09-11,city scrape,Ravenwood Manor (Historic Bywater),You are in for a very unique stay in a neighbo...,"Ours is a neighborhood made up of artists, mus...",https://a0.muscache.com/pictures/37488608/8cc1...,367223,...,4.84,4.89,"21-RSTR-18609, 22-OSTR-20720",f,1,1,0,0,1.78,Chicago
2,74498,https://www.airbnb.com/rooms/74498,20250911031349,2025-09-11,city scrape,Maison Marais 1,Maison Marais 1 is a stylish one-bedroom apart...,"This is a vibrant, diverse neighborhood of mos...",https://a0.muscache.com/pictures/73591836/a1f5...,391462,...,4.67,4.85,23-XSTR-13082,f,3,3,0,0,3.75,Chicago
4,79609,https://www.airbnb.com/rooms/79609,20250911031349,2025-09-11,city scrape,Bywater's Original & Finest,The Art of Hospitality,"First settled in 1806, Bywater is known for it...",https://a0.muscache.com/pictures/5c5da2eb-7434...,428909,...,4.84,4.94,"23-ISTR-02823, 23-OSTR-02823",f,1,1,0,0,2.86,Chicago
5,80869,https://www.airbnb.com/rooms/80869,20250911031349,2025-09-11,city scrape,"Frenchmen House ""Red Room""",Victorian-style 100+ year old house on Frenchm...,I love that my neighborhood is just far enough...,https://a0.muscache.com/pictures/b39e91a7-f5dd...,437783,...,4.72,4.84,24-XSTR-08500,t,2,0,2,0,5.65,Chicago

In [ ]:
# 1. Check the data type first
print("Before cleaning:", df['price'].dtype)

# 2. Remove '$' and ',' signs
# We treat the column as a string (.str), replace the symbols with nothing, and convert to float.
df['price'] = df['price'].astype(str).str.replace('$', '').str.replace(',', '')
df['price'] = pd.to_numeric(df['price'])

# Check again
print("After cleaning:", df['price'].dtype)

Before cleaning: float64
After cleaning: float64

In [ ]:
# 1. Fill missing review data with 0
df['reviews_per_month'] = df['reviews_per_month'].fillna(0)
df['number_of_reviews'] = df['number_of_reviews'].fillna(0)

# 2. Drop rows that are missing essential identity info
# We are dropping rows where 'host_name' or 'name' is missing
df.dropna(subset=['host_name', 'name'], inplace=True)

# 3. Check if any nulls remain (Should be 0 for these columns)
print("Remaining Nulls in Reviews:", df['reviews_per_month'].isnull().sum())
print("Remaining Nulls in Host Name:", df['host_name'].isnull().sum())

Remaining Nulls in Reviews: 0
Remaining Nulls in Host Name: 0

In [ ]:
# --- Transformation 1: Price Category ---
def categorize_price(price):
    if price < 100:
        return 'Budget (<$100)'
    elif price <= 300:
        return 'Standard ($100-$300)'
    else:
        return 'Premium (>$300)'

df['Price Category'] = df['price'].apply(categorize_price)

# --- Transformation 2: Host Type ---
# Count how many listings each host has
host_counts = df['host_id'].value_counts()

# Map that count back to the original dataframe
df['Host Listings Count'] = df['host_id'].map(host_counts)

# Create the label
def categorize_host(count):
    if count == 1:
        return 'Single Host'
    else:
        return 'Multi-Listing Host'

df['Host Type'] = df['Host Listings Count'].apply(categorize_host)

# Preview the new magic columns
print(df[['name', 'price', 'Price Category', 'Host Type']].head())

                                 name  price        Price Category  \
0      Fully Furnished Cozy Apartment   61.0        Budget (<$100)
1  Ravenwood Manor (Historic Bywater)  150.0  Standard ($100-$300)
2                     Maison Marais 1   85.0        Budget (<$100)
4         Bywater's Original & Finest   84.0        Budget (<$100)
5          Frenchmen House "Red Room"   80.0        Budget (<$100)

            Host Type
0         Single Host
1         Single Host
2  Multi-Listing Host
4         Single Host
5  Multi-Listing Host

In [ ]:
# --- THE GEOGRAPHIC FIX ---
# 1. Convert lat/long to numeric (just in case they are strings)
df['latitude'] = pd.to_numeric(df['latitude'], errors='coerce')
df['longitude'] = pd.to_numeric(df['longitude'], errors='coerce')

# 2. Drop rows where Latitude or Longitude is missing
# This removes the "Null Island" (Africa) problem!
df = df.dropna(subset=['latitude', 'longitude'])

# 3. Final Check
print(f"Latitude Nulls: {df['latitude'].isnull().sum()}")
print(f"Longitude Nulls: {df['longitude'].isnull().sum()}")

# Save and download the fixed file
df.to_csv('Final_Airbnb_Capstone_Data.csv', index=False)
from google.colab import files
files.download('Final_Airbnb_Capstone_Data.csv')

Latitude Nulls: 0
Longitude Nulls: 0

In [ ]:
from google.colab import files

# Save to CSV
df.to_csv('Final_Airbnb_Capstone_Data.csv', index=False)

# Trigger download to your computer
files.download('Final_Airbnb_Capstone_Data.csv')